### ISSUE TITLE
mrisurf.c build fails

### ISSUE THREAD

**Issue by nschmans** [freesurfer/freesurfer#265]
When building within the MGH NMR Center, where gcc 4.4.7 is the default compiler, and the build is configured by running just ./configure, mrisurf.c results in these compiler errors:

mrisurf.c: In function ‘MRISavgInterVertexDist’:
mrisurf.c:4331: error: unused variable ‘VtxNo’
mrisurf.c: In function ‘MRISwriteTriangularSurface’:
mrisurf.c:39619: error: assignment discards qualifiers from pointer target type

The default build flags for ./configure include -Wall and -Werror, which should work when included in the build using gcc 4.4.7, so fixing these mrisurf.c errors will restore that default behaviour.

**Comment by emtpgeek** [comment]
will look at

**Comment by emtpgeek** [comment]
bf_mrisurf_doesnt_compile
