### ISSUE TITLE
Build issue in afni.cpp

### ISSUE THREAD

**Issue by melrobin** [freesurfer/freesurfer#648]
### Platform details:

- FreeSurfer version:  Development
- Operating system name and version:  Fedora 29

### Summary
Buiild fails on afni.cpp
### Actual behavior
[ 17%] Building CXX object utils/CMakeFiles/utils.dir/afni.cpp.o
/home/melrobin/packages/freesurfer/utils/afni.cpp: In function ‘MRI* afniRead(const char*, int)’:
/home/melrobin/packages/freesurfer/utils/afni.cpp:834:30: error: passing argument 2 to restrict-qualified parameter aliases with argument 1 [-Werror=restrict]
                   swab(pmem, pmem, (size_t)(mri->width * 2));
                        ~~~~  ^~~~
cc1plus: all warnings being treated as errors

### Expected behavior

### How to replicate the behavior

### Details
Build from sources fails with the above error in parameter 2 of swab.  

Any ideas how to fix this?  
Please put URL to code or code here (if not too long).

**Comment by melrobin** [comment]
swab is define as:
proto.h:void swab(const void *from, void *to, size_t n);

Why would the source be the same as the destination in this call?

**Comment by melrobin** [comment]
This definition was wrapped in an #if 0 so i guess it does not apply.

**Comment by ahoopes** [comment]
What compiler version are you using?

**Comment by buildqa** [comment]
It compiles on CentOS7 using g++ 4.8.5, e.g.,

[ 23%] Building CXX object utils/CMakeFiles/utils.dir/afni.cpp.o
cd /home/osboxes/git/freesurfer/utils && /usr/bin/g++  -DHAVE_OPENGL -DHAVE_OPENMP -DHAVE_ZLIB -DLinux -I/home/osboxes/git/freesurfer/include -I/home/osboxes/git/freesurfer/packages/jpeg -I/home/osboxes/git/freesurfer/packages/tiff -I/home/osboxes/git/freesurfer/packages/xml2 -I/home/osboxes/git/freesurfer/packages/minc -I/home/osboxes/git/freesurfer/packages/netcdf -I/home/osboxes/git/freesurfer/packages/nrrdio -I/home/osboxes/git/freesurfer/packages/dicom -I/home/osboxes/git/freesurfer/packages/cephes -I/home/osboxes/git/freesurfer/packages/nifti -I/home/osboxes/git/freesurfer/packages/gifti -I/home/osboxes/git/packages/itk/4.13.0/include -isystem /home/osboxes/git/packages/itk/4.13.0/include/ITK-4.13  -fopenmp -Wall -Wextra -Werror -Wno-absolute-value -Wno-sign-compare -Wno-write-strings -Wno-unused-result -Wno-unused-parameter -Wno-unused-but-set-variable -fPIC -fdata-sections -ffunction-sections -Wl,--gc-sections -O2 -DNDEBUG   -Wno-for-loop-analysis -std=gnu++11 -o CMakeFiles/utils.dir/afni.cpp.o -c /home/osboxes/git/freesurfer/utils/afni.cpp

**Comment by melrobin** [comment]
Closing as this error is no longer occurring and I was not using g++ 8.3.1
